openapi: 3.0.0
info:
  title: Google Calendar API Proxy
  version: 1.0.0
servers:
  - url: https://www.googleapis.com
paths:
  /calendar/v3/calendars/primary/events:
    get:
      operationId: getCalendarEvents
      summary: Get upcoming calendar events
      parameters:
        - in: query
          name: timeMin
          schema:
            type: string
            format: date-time
          required: true
          description: Start time of the events
        - in: query
          name: maxResults
          schema:
            type: integer
          required: false
          description: Max number of events to return
        - in: query
          name: singleEvents
          schema:
            type: boolean
          required: false
          description: Expand recurring events
        - in: query
          name: orderBy
          schema:
            type: string
          required: false
          description: Order of events
      responses:
        '200':
          description: A list of calendar events
